# Default values for atm-layer-wf-process.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 00000000000.dkr.ecr.eu-south-1.amazonaws.com/xxxxxxx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

namespace: pagopa

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: DEBUG

tracing:
  enabled: "true"
  endpointBasePath: "http://jaeger-collector.default.svc.cluster.local:4317"
  enableJDBCMonitoring: "false"

objectStore:
  region: eu-south-1
  bucket_name: pagopa-dev-atm-layer-s3-wf-task-trace-logs
  resource_template_path: logs

modelServiceAddress: http://pagopa-dev-atm-layer-model.pagopa.svc.cluster.local:8080

camundaWebUser:
  address: http://pagopa-dev-atm-layer-wf-engine.pagopa.svc.cluster.local:8080
  credentialsSecretEnabled: true
  credentialsSecretName: "pagopa-dev-atm-layer-wf-process-camunda"
  credentialsSecretKeys:
    username: WEB_USER
    password: WEB_PASSWORD

transactionServiceAddress: http://pagopa-dev-atm-layer-transaction-service.pagopa.svc.cluster.local:8080

redis:
  credentialsSecretEnabled: true
  credentialsSecretName: pagopa-dev-atm-layer-wf-process-redis
  credentialsSecretKeys:
    host: host
    port: port
    hostReader: hostReader

secretProviderClass:
  enabled: true
  name: atm-layer-wf-process-secrets
  env: dev

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::00000000000:role/pagopa-dev-atm-layer-xxxxxx-serviceaccount-role
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: pagopa-dev-atm-layer-wf-process

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

deployment:
  name: pagopa-dev-atm-layer-wf-process
  annotation:
    reloader.stakater.com/auto: "true"
    secret.reloader.stakater.com/reload: pagopa-dev-atm-layer-wf-process-camunda, pagopa-dev-atm-layer-wf-process-redis

service:
  name: pagopa-dev-atm-layer-wf-process
  type: NodePort
  port: 8080

ingress:
  enabled: false
  name: pagopa-dev-atm-layer-wf-process
  className: ""
  annotations: 
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internal"
    alb.ingress.kubernetes.io/group.name: "alb-controller"
    alb.ingress.kubernetes.io/load-balancer-name: "pagopa-dev-atm-layer-alb-int"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTP": 8080}]'
  hosts:
    - host:
      paths:
        - path: /api/v1/processes
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 600m
    memory: 600Mi
  requests:
    cpu: 300m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

Release:
  Time:
    Seconds: 60
