apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: {{ index .Values.ingress.hosts 0 "paths" 0 "path" }}
            pathType: {{ index .Values.ingress.hosts 0 "paths" 0 "pathType" }}
            backend:
              service:
                name: {{ .Values.serviceAccount.name }}
                port:
                  number: {{ .Values.service.port }}