apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: atm-layer-wf-process-secrets
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "pagopa-dev-atm-layer/camunda/credentials"
          objectType: "secretsmanager"
          jmesPath: 
              - path: WEB_USER
                objectAlias: WEB_USER
              - path: WEB_PASSWORD
                objectAlias: WEB_PASSWORD
  secretObjects:
    - secretName: atm-layer-webuser
      type: Opaque
      data:
        - objectName: "WEB_USER"  # reference the corresponding parameter
          key: WEB_USER
        - objectName: "WEB_PASSWORD"  # reference the corresponding parameter
          key: WEB_PASSWORD
